<?php

$info = $this->gitInfo
	? array_filter([
		'Commit ID' => $this->gitInfo->commitId,
		'Branch name' => $this->gitInfo->branchName,
		'Deployed at' => !empty($this->gitInfo->timestamp) ? \Nette\Utils\DateTime::from($this->gitInfo->timestamp) : NULL,
		'Deployed by' => implode(' ', array_filter([
			!empty($this->gitInfo->userName)
				? $this->gitInfo->userName
				: NULL,
			!empty($this->gitInfo->userEmail)
				? '<' . $this->gitInfo->userEmail . '>'
				: NULL,
		])),
	])
	: NULL;

?>
<style class="tracy-debug">
	#tracy-debug .tracy-GitPanel td {
		white-space: nowrap;
	}

	#tracy-debug .tracy-GitPanel td:nth-child(2) {
		font-weight: bold;
	}

	#tracy-debug .tracy-GitPanel td[colspan='2'] b {
		float: right;
		margin-left: 2em;
	}
</style>

<h1>Git</h1>

<div class="tracy-inner tracy-GitPanel">
	<?php if ($info): ?>
		<table>
			<?php foreach ($info as $key => $val): ?>
				<tr>
					<?php if (iconv_strlen($val, 'UTF-8') > 25): ?>
						<td colspan=2><?= htmlspecialchars($key) ?> <b><?= htmlspecialchars($val) ?></b></td>
					<?php else: ?>
						<td><?= htmlspecialchars($key) ?></td>
						<td><?= htmlspecialchars($val) ?></td>
					<?php endif ?>
				</tr>
			<?php endforeach ?>
		</table>
	<?php else: ?>
		Could not get Git info.
	<?php endif ?>
</div>
